import type {
  WorldMaterial,
  WorldObject,
  WorldSpec,
} from "./worldspec";
import { sitePath } from "./site-path";

export interface DemoWorld {
  id: string;
  index: string;
  title: string;
  category: string;
  accent: string;
  world: WorldSpec;
  reference: string;
  referenceName: string;
  credit: string;
  sourceUrl: string;
  licenseUrl: string;
}

const material = (
  color: string,
  roughness = 0.72,
  metalness = 0,
  opacity = 1,
): WorldMaterial => ({ color, roughness, metalness, opacity });

function object(
  value: Omit<WorldObject, "rotation" | "mass" | "confidence" | "notes"> &
    Partial<Pick<WorldObject, "rotation" | "mass" | "confidence" | "notes">>,
): WorldObject {
  return {
    rotation: [0, 0, 0],
    mass: value.body === "dynamic" ? 0.5 : 0,
    confidence: 0.84,
    notes: "Vision-derived procedural primitive.",
    ...value,
  };
}

const dualMonitorDesk: WorldSpec = {
  version: "0.1",
  id: "dual_monitor_desk",
  summary:
    "A two-seat home office reconstructed from a licensed reference photo.",
  units: "meters",
  gravity: [0, -9.81, 0],
  bounds: [6.4, 3.2, 5],
  camera: {
    position: [2.8, 1.9, 4.6],
    target: [0, 0.85, -0.45],
    fov: 43,
    confidence: 0.88,
  },
  objects: [
    object({
      id: "floor",
      label: "dark office floor",
      kind: "box",
      size: [6.4, 0.1, 5],
      position: [0, -0.05, 0],
      body: "fixed",
      material: material("#34332e", 0.88),
      support: null,
      confidence: 0.91,
    }),
    object({
      id: "back_wall",
      label: "warm office wall",
      kind: "box",
      size: [6.4, 3.2, 0.1],
      position: [0, 1.6, -2.45],
      body: "fixed",
      material: material("#d9bcae", 0.96),
      support: null,
      confidence: 0.93,
    }),
    object({
      id: "window",
      label: "large back window",
      kind: "box",
      size: [2.05, 1.35, 0.04],
      position: [0, 2.02, -2.37],
      body: "fixed",
      material: material("#b9d4d2", 0.24, 0.04, 0.62),
      support: null,
      confidence: 0.9,
      notes: "Fixed translucent window plane behind the workstation.",
    }),
    ...[
      [-1.86, 1.95, 0.55, 0.72],
      [1.85, 1.86, 0.48, 0.66],
    ].map(
      ([x, y, size, confidence], index): WorldObject =>
        object({
          id: `wall_art_${index + 1}`,
          label: `framed wall art ${index + 1}`,
          kind: "box",
          size: [size, size * 0.78, 0.05],
          position: [x, y, -2.36],
          body: "fixed",
          material: material(index === 0 ? "#674e3c" : "#48625d", 0.7),
          support: null,
          confidence,
          notes: "Thin fixed wall decoration.",
        }),
    ),
    object({
      id: "desk",
      label: "built-in double desk",
      kind: "table",
      size: [3.3, 0.76, 0.8],
      position: [0, 0.38, -0.58],
      body: "fixed",
      material: material("#d8d4c8", 0.5),
      support: "floor",
      confidence: 0.94,
      notes: "Treated as fixed because the photographed desk is built into two drawer pedestals.",
    }),
    object({
      id: "drawer_left",
      label: "left yellow drawer pedestal",
      kind: "box",
      size: [0.42, 0.72, 0.62],
      position: [-1.42, 0.36, -0.58],
      body: "fixed",
      material: material("#b87918", 0.64, 0.05),
      support: "floor",
      confidence: 0.88,
    }),
    object({
      id: "drawer_right",
      label: "right yellow drawer pedestal",
      kind: "box",
      size: [0.42, 0.72, 0.62],
      position: [1.42, 0.36, -0.58],
      body: "fixed",
      material: material("#b87918", 0.64, 0.05),
      support: "floor",
      confidence: 0.88,
    }),
    object({
      id: "monitor_left",
      label: "left monitor",
      kind: "monitor",
      size: [0.78, 0.62, 0.22],
      position: [-0.77, 1.07, -0.63],
      body: "dynamic",
      mass: 5.4,
      material: material("#111416", 0.3, 0.16),
      support: "desk",
      confidence: 0.95,
    }),
    object({
      id: "monitor_right",
      label: "right monitor",
      kind: "monitor",
      size: [0.78, 0.62, 0.22],
      position: [0.72, 1.07, -0.63],
      body: "dynamic",
      mass: 5.2,
      material: material("#121517", 0.3, 0.16),
      support: "desk",
      confidence: 0.95,
    }),
    object({
      id: "speaker",
      label: "desktop speaker",
      kind: "cylinder",
      size: [0.16, 0.22, 0.16],
      position: [-0.16, 0.88, -0.61],
      body: "dynamic",
      mass: 0.7,
      material: material("#202421", 0.58),
      support: "desk",
      confidence: 0.77,
    }),
    object({
      id: "keyboard",
      label: "keyboard",
      kind: "box",
      size: [0.5, 0.04, 0.17],
      position: [0.72, 0.79, -0.3],
      body: "dynamic",
      mass: 0.72,
      material: material("#d9d4c8", 0.52),
      support: "desk",
      confidence: 0.86,
    }),
    object({
      id: "notebook",
      label: "closed notebook",
      kind: "box",
      size: [0.42, 0.035, 0.24],
      position: [-0.68, 0.7875, -0.3],
      rotation: [0, 0.04, 0],
      body: "dynamic",
      mass: 0.45,
      material: material("#b8bdba", 0.72),
      support: "desk",
      confidence: 0.76,
    }),
    object({
      id: "desk_lamp",
      label: "green desk lamp",
      kind: "lamp",
      size: [0.34, 0.5, 0.34],
      position: [1.28, 1.02, -0.58],
      rotation: [0, -0.2, 0],
      body: "dynamic",
      mass: 1.4,
      material: material("#64735a", 0.56, 0.08),
      support: "desk",
      confidence: 0.78,
      notes: "Procedural articulated appearance compiled as one rigid desk lamp.",
    }),
    object({
      id: "chair_left",
      label: "left mesh office chair",
      kind: "chair",
      size: [0.58, 0.96, 0.62],
      position: [-0.72, 0.48, 0.56],
      rotation: [0, -0.08, 0],
      body: "dynamic",
      mass: 8.2,
      material: material("#242824", 0.82),
      support: "floor",
      confidence: 0.9,
    }),
    object({
      id: "chair_right",
      label: "right leather office chair",
      kind: "chair",
      size: [0.58, 0.96, 0.62],
      position: [0.82, 0.48, 0.62],
      rotation: [0, 0.08, 0],
      body: "dynamic",
      mass: 8.5,
      material: material("#9b5e2d", 0.68),
      support: "floor",
      confidence: 0.91,
    }),
    object({
      id: "storage_box",
      label: "small floor storage box",
      kind: "box",
      size: [0.46, 0.28, 0.4],
      position: [-2.02, 0.14, 0.18],
      rotation: [0, 0.05, 0],
      body: "dynamic",
      mass: 2.2,
      material: material("#b78655", 0.8),
      support: "floor",
      confidence: 0.64,
    }),
    object({
      id: "sofa_foreground",
      label: "foreground sofa",
      kind: "sofa",
      size: [1.45, 0.86, 0.76],
      position: [-1.8, 0.43, 1.5],
      rotation: [0, 0.08, 0],
      body: "dynamic",
      mass: 31,
      material: material("#8d8f82", 0.88),
      support: "floor",
      confidence: 0.77,
      notes: "Soft upholstery is represented by conservative rigid sofa parts.",
    }),
    object({
      id: "plant_left",
      label: "left floor plant",
      kind: "plant",
      size: [0.72, 1.2, 0.72],
      position: [-2.35, 0.6, -0.8],
      body: "dynamic",
      mass: 4.2,
      material: material("#9a7653", 0.86),
      support: "floor",
      confidence: 0.84,
      notes: "Pot is the physics collider; foliage is procedural visual geometry.",
    }),
    object({
      id: "plant_right",
      label: "right floor plant",
      kind: "plant",
      size: [0.68, 1.12, 0.68],
      position: [2.18, 0.56, -0.76],
      body: "dynamic",
      mass: 3.9,
      material: material("#b38a62", 0.86),
      support: "floor",
      confidence: 0.8,
      notes: "Pot is the physics collider; foliage is procedural visual geometry.",
    }),
  ],
  uncertainties: [
    "Cables and small leaf clusters are intentionally omitted.",
    "Soft upholstery and foliage are compiled as conservative procedural proxies.",
    "Desk scale is inferred from common monitor dimensions.",
  ],
  refusal: null,
};

const packingWorkbench: WorldSpec = {
  version: "0.1",
  id: "packing_workbench",
  summary:
    "Two open cartons, a book stack, tape, and scissors on a rustic packing bench.",
  units: "meters",
  gravity: [0, -9.81, 0],
  bounds: [6.2, 3.1, 4.8],
  camera: {
    position: [3.15, 2.2, 4.55],
    target: [-0.05, 1.05, -0.08],
    fov: 42,
    confidence: 0.9,
  },
  objects: [
    object({
      id: "floor",
      label: "studio floor",
      kind: "box",
      size: [6.2, 0.1, 4.8],
      position: [0, -0.05, 0],
      body: "fixed",
      material: material("#b9b3aa", 0.88),
      support: null,
      confidence: 0.8,
    }),
    object({
      id: "back_wall",
      label: "plain white wall",
      kind: "box",
      size: [6.2, 3.1, 0.1],
      position: [0, 1.55, -2.35],
      body: "fixed",
      material: material("#ece9e4", 0.97),
      support: null,
      confidence: 0.96,
    }),
    object({
      id: "workbench",
      label: "rustic packing bench",
      kind: "table",
      size: [4.5, 0.82, 1.15],
      position: [0, 0.41, -0.05],
      body: "fixed",
      material: material("#6f4324", 0.9),
      support: "floor",
      confidence: 0.95,
      notes: "Treated as fixed because the photographed carpenter-style bench is heavy.",
    }),
    object({
      id: "carton_left",
      label: "left open carton",
      kind: "carton",
      size: [1.1, 1.2, 0.78],
      position: [-0.56, 1.43, -0.06],
      body: "dynamic",
      mass: 3.6,
      material: material("#b9824d", 0.9),
      support: "workbench",
      confidence: 0.96,
      notes: "Open carton with four procedural flaps; collider covers the box body.",
    }),
    object({
      id: "carton_right",
      label: "right open carton",
      kind: "carton",
      size: [1.1, 1.16, 0.78],
      position: [0.68, 1.41, -0.05],
      body: "dynamic",
      mass: 3.4,
      material: material("#bd8753", 0.9),
      support: "workbench",
      confidence: 0.96,
      notes: "Open carton with four procedural flaps; collider covers the box body.",
    }),
    object({
      id: "book_stack",
      label: "stack of five books",
      kind: "box",
      size: [0.74, 0.36, 0.34],
      position: [-1.55, 1.01, -0.12],
      rotation: [0, -0.03, 0],
      body: "dynamic",
      mass: 3.2,
      material: material("#d8ddd8", 0.74),
      support: "workbench",
      confidence: 0.88,
      notes: "Book stack compiled as one stable compound rigid body with five visual layers.",
    }),
    object({
      id: "tape_roll",
      label: "clear packing tape",
      kind: "cylinder",
      size: [0.24, 0.1, 0.24],
      position: [-1.96, 0.88, 0.36],
      body: "dynamic",
      mass: 0.18,
      material: material("#e3d8bd", 0.38, 0, 0.72),
      support: "workbench",
      confidence: 0.9,
      notes: "Tape roll is approximated by a translucent cylinder.",
    }),
    object({
      id: "scissors",
      label: "packing scissors",
      kind: "box",
      size: [0.29, 0.04, 0.08],
      position: [-1.51, 0.85, 0.39],
      rotation: [0, 0.18, 0],
      body: "dynamic",
      mass: 0.08,
      material: material("#d9d9d4", 0.32, 0.46),
      support: "workbench",
      confidence: 0.74,
      notes: "Scissors are represented by a single thin rigid proxy.",
    }),
  ],
  uncertainties: [
    "Cardboard flap angles are approximate and excluded from collision.",
    "Book titles and the tape-roll hole are visual details, not task geometry.",
    "Carton contents and mass distribution are unknown.",
  ],
  refusal: null,
};

const cafeCorner: WorldSpec = {
  version: "0.1",
  id: "cafe_corner",
  summary:
    "A compact café corner with two tables, three chairs, and wall-supported props.",
  units: "meters",
  gravity: [0, -9.81, 0],
  bounds: [5.8, 3.2, 5],
  camera: {
    position: [2.65, 1.86, 4.35],
    target: [-0.08, 0.84, -0.28],
    fov: 44,
    confidence: 0.86,
  },
  objects: [
    object({
      id: "floor",
      label: "gray café tile",
      kind: "box",
      size: [5.8, 0.1, 5],
      position: [0, -0.05, 0],
      body: "fixed",
      material: material("#77736a", 0.78),
      support: null,
      confidence: 0.87,
    }),
    object({
      id: "back_wall",
      label: "textured café wall",
      kind: "box",
      size: [5.8, 3.2, 0.1],
      position: [0, 1.6, -2.45],
      body: "fixed",
      material: material("#a78d70", 0.95),
      support: null,
      confidence: 0.9,
    }),
    object({
      id: "mesh_panel_left",
      label: "left black mesh panel",
      kind: "box",
      size: [0.9, 2.5, 0.04],
      position: [-0.45, 1.7, -2.36],
      body: "fixed",
      material: material("#1f211f", 0.64, 0.16),
      support: null,
      confidence: 0.92,
      notes: "Fixed wall panel represented as a thin dark plane.",
    }),
    object({
      id: "mesh_panel_right",
      label: "right black mesh panel",
      kind: "box",
      size: [0.68, 1.95, 0.04],
      position: [1.5, 1.62, -2.36],
      body: "fixed",
      material: material("#202220", 0.64, 0.16),
      support: null,
      confidence: 0.82,
      notes: "Partially visible fixed wall panel.",
    }),
    object({
      id: "back_table",
      label: "back café table",
      kind: "table",
      size: [1.1, 0.76, 0.7],
      position: [-0.35, 0.38, -0.6],
      body: "dynamic",
      mass: 14,
      material: material("#754522", 0.58),
      support: "floor",
      confidence: 0.88,
    }),
    object({
      id: "front_table",
      label: "foreground café table",
      kind: "table",
      size: [1.35, 0.76, 0.85],
      position: [0.9, 0.38, 0.68],
      body: "dynamic",
      mass: 16,
      material: material("#a9682f", 0.56),
      support: "floor",
      confidence: 0.82,
    }),
    object({
      id: "chair_center",
      label: "center café chair",
      kind: "chair",
      size: [0.58, 0.96, 0.58],
      position: [-0.48, 0.48, 0.26],
      rotation: [0, 0.06, 0],
      body: "dynamic",
      mass: 6.5,
      material: material("#3d291d", 0.78),
      support: "floor",
      confidence: 0.93,
    }),
    object({
      id: "chair_left",
      label: "left café chair",
      kind: "chair",
      size: [0.56, 0.94, 0.56],
      position: [-1.48, 0.47, 0.62],
      rotation: [0, -0.12, 0],
      body: "dynamic",
      mass: 6.2,
      material: material("#3c2a20", 0.78),
      support: "floor",
      confidence: 0.72,
    }),
    object({
      id: "chair_right",
      label: "foreground café chair",
      kind: "chair",
      size: [0.58, 0.96, 0.58],
      position: [0.78, 0.48, 1.55],
      rotation: [0, 0.03, 0],
      body: "dynamic",
      mass: 6.5,
      material: material("#3a2920", 0.78),
      support: "floor",
      confidence: 0.91,
      notes: "Placed in front of the foreground table to match the source occlusion.",
    }),
    object({
      id: "wall_shelf_left",
      label: "left wall shelf",
      kind: "box",
      size: [1.05, 0.08, 0.3],
      position: [-0.45, 1.78, -2.18],
      body: "fixed",
      material: material("#5c361d", 0.6),
      support: null,
      confidence: 0.84,
    }),
    object({
      id: "shelf_plant_left",
      label: "flowers on left shelf",
      kind: "plant",
      size: [0.28, 0.42, 0.28],
      position: [-0.45, 2.04, -2.14],
      body: "dynamic",
      mass: 0.62,
      material: material("#b7c1b8", 0.7),
      support: "wall_shelf_left",
      confidence: 0.76,
      notes: "Pot collider with procedural flower-like foliage.",
    }),
    object({
      id: "wall_shelf_right",
      label: "right wall shelf",
      kind: "box",
      size: [0.72, 0.08, 0.3],
      position: [1.5, 1.5, -2.18],
      body: "fixed",
      material: material("#5c361d", 0.6),
      support: null,
      confidence: 0.77,
    }),
    object({
      id: "shelf_plant_right",
      label: "small right shelf plant",
      kind: "plant",
      size: [0.24, 0.34, 0.24],
      position: [1.5, 1.72, -2.14],
      body: "dynamic",
      mass: 0.46,
      material: material("#d2d0c4", 0.72),
      support: "wall_shelf_right",
      confidence: 0.72,
      notes: "Pot collider with procedural foliage.",
    }),
  ],
  uncertainties: [
    "The foreground table is partly cropped by the source image.",
    "Mesh wall panels and chair upholstery are simplified.",
    "The partially visible left chair has lower pose confidence.",
  ],
  refusal: null,
};

const patioDining: WorldSpec = {
  version: "0.1",
  id: "patio_dining",
  summary:
    "A high-contrast patio dining setup reconstructed from a portrait photo.",
  units: "meters",
  gravity: [0, -9.81, 0],
  bounds: [6.2, 3.3, 5.2],
  camera: {
    position: [0, 1.78, 4.7],
    target: [0, 0.94, -0.52],
    fov: 41,
    confidence: 0.92,
  },
  objects: [
    object({
      id: "floor",
      label: "wood patio floor",
      kind: "box",
      size: [6.2, 0.1, 5.2],
      position: [0, -0.05, 0],
      body: "fixed",
      material: material("#754421", 0.72),
      support: null,
      confidence: 0.92,
    }),
    object({
      id: "back_wall",
      label: "dark slatted wall",
      kind: "box",
      size: [6.2, 3.3, 0.1],
      position: [0, 1.65, -2.55],
      body: "fixed",
      material: material("#1d282b", 0.8, 0.08),
      support: null,
      confidence: 0.94,
    }),
    object({
      id: "table",
      label: "weathered patio table",
      kind: "table",
      size: [1.9, 0.76, 0.88],
      position: [0, 0.38, -0.48],
      body: "dynamic",
      mass: 19,
      material: material("#9f8e73", 0.86),
      support: "floor",
      confidence: 0.94,
    }),
    object({
      id: "chair_front",
      label: "front woven chair",
      kind: "chair",
      size: [0.62, 0.98, 0.62],
      position: [0, 0.49, 0.82],
      body: "dynamic",
      mass: 5.8,
      material: material("#e5e2d7", 0.88),
      support: "floor",
      confidence: 0.95,
    }),
    object({
      id: "chair_back",
      label: "back woven chair",
      kind: "chair",
      size: [0.62, 0.98, 0.62],
      position: [0, 0.49, -1.42],
      rotation: [0, Math.PI, 0],
      body: "dynamic",
      mass: 5.8,
      material: material("#e7e4da", 0.88),
      support: "floor",
      confidence: 0.89,
    }),
    object({
      id: "table_pot",
      label: "white tabletop plant",
      kind: "plant",
      size: [0.38, 0.62, 0.38],
      position: [0.08, 1.08, -0.43],
      body: "dynamic",
      mass: 1.2,
      material: material("#ece8dd", 0.64),
      support: "table",
      confidence: 0.91,
      notes: "Pot collider with procedural succulent foliage.",
    }),
    object({
      id: "cactus_pot",
      label: "tall tabletop cactus",
      kind: "plant",
      size: [0.32, 0.72, 0.32],
      position: [0.72, 1.13, -0.56],
      body: "dynamic",
      mass: 1.45,
      material: material("#80664c", 0.86),
      support: "table",
      confidence: 0.93,
      notes: "Cactus with pot collider and procedural stems.",
    }),
    ...[
      [-0.56, 1.62, 0.54, 0.88],
      [0.25, 1.83, 0.36, 0.8],
      [0.73, 1.55, 0.3, 0.72],
    ].map(
      ([x, y, diameter, confidence], index): WorldObject =>
        object({
          id: `wall_disc_${index + 1}`,
          label: `woven wall disc ${index + 1}`,
          kind: "cylinder",
          size: [diameter, 0.05, diameter],
          position: [x, y, -2.47],
          rotation: [Math.PI / 2, 0, 0],
          body: "fixed",
          material: material("#a97139", 0.86),
          support: null,
          confidence,
          notes: "Thin fixed wall decoration.",
        }),
    ),
    object({
      id: "door_left",
      label: "left glass door",
      kind: "box",
      size: [0.72, 2.15, 0.08],
      position: [-2.25, 1.075, -2.45],
      body: "fixed",
      material: material("#c8d0cc", 0.35, 0.08, 0.55),
      support: null,
      confidence: 0.8,
    }),
    object({
      id: "door_right",
      label: "right timber door",
      kind: "box",
      size: [0.72, 2.15, 0.08],
      position: [2.25, 1.075, -2.45],
      body: "fixed",
      material: material("#745035", 0.78),
      support: null,
      confidence: 0.82,
    }),
    object({
      id: "pendant_left",
      label: "left woven pendant lamp",
      kind: "lamp",
      size: [0.78, 1.08, 0.78],
      position: [-0.76, 2.66, -0.6],
      body: "fixed",
      material: material("#d5b98d", 0.92),
      support: null,
      confidence: 0.96,
      notes: "Fixed pendant lamp with procedural cord and woven-shade proxy.",
    }),
    object({
      id: "pendant_right",
      label: "right woven pendant lamp",
      kind: "lamp",
      size: [0.78, 1.08, 0.78],
      position: [0.76, 2.66, -0.6],
      body: "fixed",
      material: material("#d7bd93", 0.92),
      support: null,
      confidence: 0.96,
      notes: "Fixed pendant lamp with procedural cord and woven-shade proxy.",
    }),
    object({
      id: "wall_heater",
      label: "wall-mounted patio heater",
      kind: "box",
      size: [0.74, 0.24, 0.16],
      position: [0, 2.69, -2.31],
      body: "fixed",
      material: material("#625e55", 0.5, 0.42),
      support: null,
      confidence: 0.86,
    }),
  ],
  uncertainties: [
    "Woven chair topology is represented by conservative upholstered-chair primitives.",
    "Woven lamp shades and foliage use lightweight procedural proxies.",
    "The portrait reference crops the lateral room extent.",
  ],
  refusal: null,
};

export const DEMO_WORLDS: DemoWorld[] = [
  {
    id: "office",
    index: "01",
    title: "Dual monitor desk",
    category: "Workspace · 20 bodies",
    accent: "#d8ff3e",
    world: dualMonitorDesk,
    reference: sitePath("/demo-office.jpg"),
    referenceName: "dual-monitor-office.jpg",
    credit: "Photo · Annie Spratt",
    sourceUrl:
      "https://unsplash.com/photos/a-desk-with-two-computer-monitors-and-a-chair-6pMI--IXV-8",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    id: "packing",
    index: "02",
    title: "Packing workbench",
    category: "Rigid props · 8 bodies",
    accent: "#ff795d",
    world: packingWorkbench,
    reference: sitePath("/demo-boxes.jpg"),
    referenceName: "packing-workbench.jpg",
    credit: "Photo · Kaboompics.com",
    sourceUrl:
      "https://www.pexels.com/photo/carton-boxes-and-stacked-books-on-table-4498124/",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    id: "cafe",
    index: "03",
    title: "Café corner",
    category: "Occlusion · 13 bodies",
    accent: "#8eb7ff",
    world: cafeCorner,
    reference: sitePath("/demo-cafe.jpg"),
    referenceName: "cafe-corner.jpg",
    credit: "Photo · Zulfahmi Al Ridhawi",
    sourceUrl:
      "https://unsplash.com/photos/a-cozy-cafe-interior-with-tables-and-chairs-7ZTH7KsF8NY",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    id: "patio",
    index: "04",
    title: "Patio dining",
    category: "Portrait view · 15 bodies",
    accent: "#d699ff",
    world: patioDining,
    reference: sitePath("/demo-dining.jpg"),
    referenceName: "patio-dining.jpg",
    credit: "Photo · Rachel Claire",
    sourceUrl:
      "https://www.pexels.com/photo/dining-table-with-chairs-in-home-interior-design-6123238/",
    licenseUrl: "https://www.pexels.com/license/",
  },
];
